### ISSUE TITLE
Consideration: Incorporate features of Cloudstomp for launching cloud instance

### ISSUE THREAD

**Issue by Fmstrat** [f0cker/crackq#2]
Hi all,

I developed Cloudstomp for a similar reason (machine learning and current user password validation): https://github.com/Fmstrat/cloudstomp

It's main feature is it is built to grab the most affordable AWS GPU spot instance to run hashcat. This logic could be a great addition to CrackQ, and it is already written in Python.

Basically, launch the cli, choose a price/instance, and CloudQ gets launched in AWS.

It also supports statelessness by storing encrypted responses in S3 for if the spot instance goes down.

Thoughts?

**Comment by f0cker** [comment]
Thanks for the suggestion. Though this looks like it could be useful for AWS users, I think they are best kept separate. The reasons are to avoid adding unnecessary complexity to the CrackQ codebase and also because the AWS/cloud usability is more of a pleasant side-effect of the application design, rather than a priority feature.
